# Generated by Django 4.1.5 on 2023-01-16 08:20

import AppApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=AppApi.models.avatar_path),
        ),
    ]
