# Generated by Django 4.1.5 on 2023-02-24 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0005_user_is_private_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_user',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
