# Generated by Django 4.1.5 on 2023-03-15 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0006_user_blocked_user_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
