# Generated by Django 4.1.5 on 2023-03-15 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0007_messages_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='messages',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
