# Generated by Django 4.1.5 on 2023-03-30 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0008_remove_messages_deleted_by_messages_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_to',
            field=models.ManyToManyField(blank=True, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
