# Generated by Django 4.1.5 on 2023-03-31 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0009_user_following_user_requested_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='messages',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
