# Generated by Django 4.1.5 on 2023-04-01 09:52

import AppApi.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0010_remove_messages_deleted_by_messages_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='avatar/default.jpg', help_text='Profile Picture', null=True, upload_to=AppApi.models.avatar_path, verbose_name='Profile Picture'),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('notification_receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to=settings.AUTH_USER_MODEL)),
                ('notification_sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
