# Generated by Django 4.1.5 on 2023-04-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0011_alter_user_avatar_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
