# Generated by Django 4.1.5 on 2023-04-07 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0012_notifications_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='deleted_by',
        ),
        migrations.AlterField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messages',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
