# Generated by Django 4.1.5 on 2023-05-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0015_messages_is_deleted_remove_messages_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
